export const urls = [
  "https://www.thegreatcourses.com/courses/foundations-of-eastern-civilization.html",
  "https://www.thegreatcourses.com/courses/understanding-imperial-china-dynasties-life-and-culture.html",
  "https://www.thegreatcourses.com/courses/celtic-world.html",
  "https://www.thegreatcourses.com/courses/the-learning-brain.html",
  "https://www.thegreatcourses.com/courses/learning-statistics-concepts-and-applications-in-r.html",
  "https://www.thegreatcourses.com/courses/your-best-brain-the-science-of-brain-improvement.html",
  "https://www.thegreatcourses.com/courses/plant-science-an-introduction-to-botany.html",
  "https://www.thegreatcourses.com/courses/an-economic-history-of-the-world-since-1400.html",
  "https://www.thegreatcourses.com/courses/building-a-better-vocabulary.html",
  "https://www.thegreatcourses.com/courses/understanding-modern-electronics.html",
  "https://www.thegreatcourses.com/courses/brain-myths-exploded-lessons-from-neuroscience.html",
  "https://www.thegreatcourses.com/courses/big-data-how-data-analytics-is-transforming-the-world.html",
  "https://www.thegreatcourses.com/courses/how-the-world-learns-comparative-educational-systems.html",
  "https://www.thegreatcourses.com/courses/redefining-reality-the-intellectual-implications-of-modern-science.html",
  "https://www.thegreatcourses.com/courses/understanding-the-inventions-that-changed-the-world.html",
  "https://www.thegreatcourses.com/courses/30-masterpieces-of-the-ancient-world.html",
  "https://www.thegreatcourses.com/courses/science/engineering-technology/understanding-the-world-s-greatest-structures-science-and-innovation-from-antiquity-to-modernity.html",
  "https://www.thegreatcourses.com/courses/a-history-of-eastern-europe.html",
  "https://www.thegreatcourses.com/courses/how-you-decide-the-science-of-human-decision-making.html",
  "https://www.thegreatcourses.com/courses/the-black-death-the-worlds-most-devastating-plague.html",
  "https://www.thegreatcourses.com/courses/history-of-ancient-egypt.html",
  "https://www.thegreatcourses.com/courses/your-deceptive-mind-a-scientific-guide-to-critical-thinking-skills.html",
  "https://www.thegreatcourses.com/courses/the-science-of-information-from-language-to-black-holes.html",
  "https://www.thegreatcourses.com/courses/the-science-of-energy-resources-and-power-explained.html",
  "https://www.thegreatcourses.com/courses/being-human-life-lessons-from-the-frontiers-of-science.html",
  "https://www.thegreatcourses.com/courses/the-surveillance-state-big-data-freedom-and-you.html",
  "https://www.thegreatcourses.com/courses/history-of-the-ancient-world-a-global-perspective.html",
  "https://www.thegreatcourses.com/courses/the-world-s-greatest-geological-wonders-36-spectacular-sites.html",
  "https://www.thegreatcourses.com/courses/archaeology-an-introduction-to-the-world-s-greatest-sites.html",
  "https://www.thegreatcourses.com/courses/the-aging-brain.html",
  "https://www.thegreatcourses.com/courses/the-everyday-guide-to-wine.html",
  "https://www.thegreatcourses.com/courses/our-night-sky.html",
  "https://www.thegreatcourses.com/courses/an-introduction-to-formal-logic.html",
  "https://www.thegreatcourses.com/courses/the-positive-mind-mindfulness-and-the-science-of-happiness.html",
  "https://www.thegreatcourses.com/courses/english-grammar-boot-camp.html",
  "https://www.thegreatcourses.com/courses/optimizing-brain-fitness.html",
  "https://www.thegreatcourses.com/courses/the-inexplicable-universe-unsolved-mysteries.html",
  "https://www.thegreatcourses.com/courses/practicing-mindfulness-an-introduction-to-meditation.html",
  "https://www.thegreatcourses.com/courses/cognitive-behavioral-therapy-techniques-for-retraining-your-brain.html",
  "https://www.thegreatcourses.com/courses/secrets-of-mental-math.html",
  // "https://www.thegreatcoursesplus.com/cities-of-the-ancient-world",
  // "https://www.thegreatcoursesplus.com/english-in-america-a-linguistic-history",
];

export const htmlCrufts = [
  /<div class="lectures-bar clearfix">/g,
  /<div class="lectures-container-title">[\d]+ lectures<\/div>/g,
  /<div class="course-counters">/g,
  /<span class="vert-divider">&#xA0;\|&#xA0;<\/span>/g,
  /<span>Average [\d]+ minutes each<\/span>/g,
  /<\/div>/g,
  /<div>/g,
  /<\/li>/g,
  /<li>/g,
  /<\/ul>/g,
  /<ul class="lectures-list">/g,
  /<div class="lecture-counter">/g,
  /<a href="javascript:void\(0\)" class="lectures-close-balloon left">x<\/a>/g,
  /<a href="javascript:void\(0\)" class="lectures-close-balloon right">x<\/a>/g
];
